#! /nix/store/hh833qm6lgb6cgr7z9vxkb72wikr4wwz-bash-4.4-p12/bin/bash -e
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home"
exec "/nix/store/d7sj4n97kdk4rczbk6cnq34z535c2mrj-apache-maven-3.5.2/maven/bin/mvn"  "${extraFlagsArray[@]}" "$@"
